

/*
    JOIN SOLUTION
*/
SELECT c.NAME FROM CITY AS c
INNER JOIN COUNTRY AS ct
ON c.COUNTRYCODE = ct.CODE
WHERE ct.CONTINENT = 'Africa';



/*
    SUBQUERY SOLUTION
*/
SELECT NAME FROM CITY
WHERE COUNTRYCODE IN (
    SELECT CODE FROM COUNTRY
    WHERE CONTINENT = 'Africa'
);


/*
    CARTESIAN PRODUCT SOLUTION
*/
SELECT NAME FROM CITY, COUNTRY
WHERE
    CITY.COUNTRYCODE = COUNTRY.CODE AND
    COUNTRY.CONTINENT = 'Africa';