
/*
    INNER JOIN SOLUTION
*/
SELECT con.CONTINENT, FLOOR( AVG( c.POPULATION) ) FROM CITY AS c
INNER JOIN
    COUNTRY AS con
ON c.COUNTRYCODE = con.CODE
GROUP BY con.CONTINENT;



/*
    CARTESIAN PRODUCT SOLUTION
*/
SELECT con.CONTINENT, FLOOR( AVG(c.POPULATION) )
FROM CITY AS c, COUNTRY as con
WHERE c.COUNTRYCODE = con.CODE
GROUP BY con.CONTINENT;