/* REGULAR EXPRESSION SOLUTION */
SELECT DISTINCT CITY FROM STATION
WHERE
    REGEXP_LIKE( CITY, '^[^AEIOU]');

/* HARD CODED SOLUTION */
SELECT DISTINCT CITY FROM STATION
WHERE
    CITY NOT LIKE 'A%' AND
    CITY NOT LIKE 'E%' AND
    CITY NOT LIKE 'I%' AND
    CITY NOT LIKE 'O%' AND
    CITY NOT LIKE 'U%';


/* SUBSTRING SOLUTION */
SELECT DISTINCT CITY FROM STATION 
WHERE
    SUBSTR( CITY, 0, 1) NOT IN ('A','E','I','O','U');