
/*
    SORT SOLUTION
*/
SELECT FORMAT(LONG_W, 4) FROM STATION
WHERE
    LAT_N < 137.2345
ORDER BY LONG_W DESC
LIMIT 1;


/*
    SUBQUERY SOLUTION
*/
SELECT FORMAT(LONG_W, 4) FROM STATION
WHERE
    LAT_N = (
        SELECT MAX(LAT_N) FROM STATION
        WHERE
            LAT_N < 137.2345
    );