/* HARD CODE SOLUTION */
SELECT DISTINCT CITY FROM STATION
WHERE
    CITY NOT LIKE '%a' AND
    CITY NOT LIKE '%e' AND
    CITY NOT LIKE '%i' AND
    CITY NOT LIKE '%o' AND
    CITY NOT LIKE '%u';


/* SUBSTRING SOLUTION */
SELECT DISTINCT CITY FROM STATION
WHERE
    SUBSTR(CITY, -1) NOT IN ('a','e','i','o','u');


/* REGULAR EXPRESSION SOLUTION */
SELECT DISTINCT CITY FROM STATION
WHERE
    REGEXP_LIKE( CITY, '[^aeiou]$');