
/*  HARDCODED SOLUTION

SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE 'A%'
OR CITY LIKE 'E%'
OR CITY LIKE 'I%'
OR CITY LIKE 'O%'
OR CITY LIKE 'U%';

*/

/*  SUBSTRING SOLUTION 

SELECT DISTINCT CITY FROM STATION
WHERE
    SUBSTRING(CITY, 1, 1) IN ('A','E','I','O','U');
    
*/



/* REGULAR EXPRESSION SOLUTION */
SELECT DISTINCT CITY FROM STATION
WHERE REGEXP_LIKE( CITY, '^[AEIOU]') ;