
/*  HARD CODED SOLUTION */
SELECT DISTINCT CITY FROM STATION
WHERE
    CITY LIKE '%A' OR
    CITY LIKE '%E' OR
    CITY LIKE '%I' OR
    CITY LIKE '%O' OR
    CITY LIKE '%U';

/*  SUBSTRING SOLUTION */
SELECT DISTINCT CITY FROM STATION
WHERE
    SUBSTR(CITY, -1) IN ('a','e','i','o','u');


/*  REGEX EXPRESSION SOLUTION */
SELECT DISTINCT CITY FROM STATION
WHERE
    REGEXP_LIKE( CITY, '[AEIOU]$');